<a href="https://colab.research.google.com/github/Aalavikhan/ML_-Tensorflow-/blob/main/TF_1_var%2Cind%2Cfunc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Tensors

In [48]:
import tensorflow as tf


In [49]:
zero_d_tensor= tf.constant(4)
print(zero_d_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [50]:
zero_d_tensor.shape

TensorShape([])

In [51]:
one_d_tensor=tf.constant([1,2,3],dtype=tf.int64)
print(one_d_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [52]:
two_d_tensor=tf.constant([[1,2,3],
                         [4,5,6]] , dtype=tf.float32)
print(two_d_tensor)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [53]:
three_d_tensor=tf.constant([[[1,2,3],
                             [4,5,6],
                             [7,8,9]],
                            [[1,2,3],
                            [5,6,7],
                            [9,11,12]]])
print(three_d_tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 1  2  3]
  [ 5  6  7]
  [ 9 11 12]]], shape=(2, 3, 3), dtype=int32)


##Casting


In [54]:
tensor1=tf.constant([[1,2.0,3.5],
                    [4,5,6]], dtype=tf.float32)

In [55]:
print(tensor1)

tf.Tensor(
[[1.  2.  3.5]
 [4.  5.  6. ]], shape=(2, 3), dtype=float32)


In [56]:
casted_tensor1=tf.cast(tensor1, dtype=tf.int64)
print(casted_tensor1)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)


##Numpy array to tensor


In [57]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [58]:
converted_to_tensor= tf.convert_to_tensor(arr)
print(converted_to_tensor)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)


##Identity matrix using tensor

copy eye data from tensorflow website:

In [59]:
eye= tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [60]:
eye= tf.eye(
    num_rows=3,
    num_columns=5,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]], shape=(3, 5), dtype=float32)


In [61]:
eye= tf.eye(
    num_rows=5,
    num_columns=3,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [62]:
eye= tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


##Fill

In [63]:
fill= tf.fill(
    [3,4], value=69, name=None, layout=None
)
print(fill)

tf.Tensor(
[[69 69 69 69]
 [69 69 69 69]
 [69 69 69 69]], shape=(3, 4), dtype=int32)


##Ones

In [64]:
tensor_one=tf.ones(
    [3,4],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)

print(tensor_one)

#see ones like tensor, zeros, shape, rank, size, random.normal too
#sem shit

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


##Random Normal

In [65]:
random=tf.random.normal(
    [3,4],
    mean=100.0,
    stddev=0.5,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random)

tf.Tensor(
[[100.12243   99.68028  100.58425   99.61109 ]
 [100.14324  100.04326  100.323265 100.074684]
 [ 99.46311   99.64142   99.49879   99.42075 ]], shape=(3, 4), dtype=float32)


##Uniform Normal

In [69]:
uniform = tf.random.uniform(
    [5,],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(uniform)

tf.Tensor([38.57608  80.63269  52.386963 96.720215 30.572283], shape=(5,), dtype=float32)


In [76]:
# matching set_seed and seed value argument inside random.uniform function will
# generate the same random patterns
tf.random.set_seed(4)
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=14))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))

tf.Tensor([2 0 1], shape=(3,), dtype=int32)
tf.Tensor([0 2 0], shape=(3,), dtype=int32)


In [75]:
tf.random.set_seed(4)
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=14))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))

tf.Tensor([2 0 1], shape=(3,), dtype=int32)
tf.Tensor([0 2 0], shape=(3,), dtype=int32)


##Tensor Indexing

In [80]:
tensor_index=[1,2,3,4,5,6,7,8,9]
print(tensor_index[0:7])
print(tensor_index[0:7:2])

[1, 2, 3, 4, 5, 6, 7]
[1, 3, 5, 7]


In [84]:
tensor_two_d=tf.constant([[1,2,3],
                          [4,5,6],
                          [7,8,9]])
print(tensor_two_d[0:2,0:2])
print(tensor_two_d[2,:])
print(tensor_two_d[:,1])
print(tensor_two_d[...,1])

tf.Tensor(
[[1 2]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor([7 8 9], shape=(3,), dtype=int32)
tf.Tensor([2 5 8], shape=(3,), dtype=int32)
tf.Tensor([2 5 8], shape=(3,), dtype=int32)


In [85]:
three_d_tensor=tf.constant([[[1,2,3],
                             [4,5,6],
                             [7,8,9]],
                            [[1,2,3],
                            [5,6,7],
                            [9,11,12]]])
print(three_d_tensor[1,:,:])

tf.Tensor(
[[ 1  2  3]
 [ 5  6  7]
 [ 9 11 12]], shape=(3, 3), dtype=int32)


##Math Functions


In [ ]:
#abs, add, multiply, subtract, divide, divide_no_nan